<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Artikel;
use Illuminate\Support\Str;
use Carbon\Carbon;

class ArtikelSeeder extends Seeder
{
    public function run(): void
    {
        $artikelData = [
            [
                'judul' => 'Indonesia Tuntaskan Negosiasi Perdagangan dengan Blok Eropa, Fokus Sektor Hijau',
                'slug' => 'indonesia-tuntaskan-negosiasi-perdagangan-dengan-blok-eropa-fokus-sektor-hijau',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/l3p6GAB5vn3rYNCGl0D061YMHwhhva76UGM9YGY6.jpg',
                'ringkasan' => 'Kabar terbaru dari Kementerian Perdagangan mengumumkan penuntasan negosiasi perjanjian dagang komprehensif dengan Uni Eropa, dengan fokus utama pada produk ramah lingkungan dan keberlanjutan.',
                'isi' => 'Indonesia dan Uni Eropa (UE) telah berhasil menyelesaikan putaran negosiasi terakhir untuk perjanjian Comprehensive Economic Partnership Agreement (CEPA). Penandatanganan akhir diharapkan terjadi pada kuartal mendatang. Menteri Koordinator Bidang Perekonomian menyatakan bahwa perjanjian ini akan membuka akses pasar yang jauh lebih luas bagi produk-produk unggulan Indonesia. Fokus utama dalam kesepakatan ini adalah pengakuan UE terhadap standar keberlanjutan Indonesia, terutama untuk produk kelapa sawit yang ramah lingkungan dan turunan mineral yang diolah di dalam negeri. Pemerintah berharap perjanjian ini akan mendongkrak ekspor non-migas Indonesia hingga 15% dalam lima tahun ke depan. Selain perdagangan barang, CEPA juga mencakup perjanjian terkait investasi dan layanan. Ini diharapkan menarik investasi asing langsung ke sektor energi terbarukan dan industri digital. Pemerintah kini sedang menyiapkan regulasi pendukung untuk memastikan pelaku usaha domestik siap memanfaatkan peluang pasar baru ini.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Mendagri Perintahkan Pemda Waspada, Stabilitas Harga Pangan Jadi Prioritas Utama Akhir Tahun',
                'slug' => 'mendagri-perintahkan-pemda-waspada-stabilitas-harga-pangan-jadi-prioritas-utama-akhir-tahun',
                'kategori' => 'Nasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/WARuGbODTbbdkkdnAizZHYSf3gMeAYsMJ3pAZJn8.jpg',
                'ringkasan' => 'Menteri Dalam Negeri (Mendagri) menegaskan pentingnya intervensi aktif pemerintah daerah (Pemda) untuk menjaga stabilitas harga pangan, terutama menjelang perayaan akhir tahun yang rentan terhadap inflasi.',
                'isi' => 'Jakarta, 17 Oktober 2025 - Menteri Dalam Negeri Muhammad Tito Karnavian kembali menekankan kepada seluruh kepala daerah pentingnya menjaga stabilitas harga pangan di wilayah masing-masing. Menurut Mendagri, stabilitas harga merupakan kunci untuk menjaga daya beli masyarakat dan mengendalikan inflasi nasional. Hal ini diungkapkan dalam rapat koordinasi nasional yang membahas kesiapan daerah menghadapi lonjakan permintaan di akhir tahun. Mendagri menegaskan bahwa daerah tidak boleh autopilot atau berjalan tanpa intervensi. Pemda diimbau untuk rutin menggelar rapat, memiliki data akurat mengenai pasokan dan permintaan komoditas, serta berani melakukan intervensi pasar seperti menggelar operasi pasar atau Gerakan Pangan Murah (GPM) serentak. "Jika tidak ada upaya intervensi, maka harga tidak akan terkendali," tegas Mendagri. Arahan ini sejalan dengan fokus pemerintah pusat yang menjadikan ketahanan dan stabilitas pangan sebagai agenda prioritas. Dengan adanya langkah sinergis dari pusat hingga daerah, diharapkan lonjakan harga bahan pokok seperti beras, cabai, dan bawang dapat diminimalisir, sehingga masyarakat dapat menyambut pergantian tahun dengan lebih tenang tanpa terbebani inflasi yang tinggi.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'DPR Kritik Kenaikan Iuran BPJS Kesehatan: Solusi Jangan Bebani Rakyat',
                'slug' => 'dpr-kritik-kenaikan-iuran-bpjs-kesehatan-solusi-jangan-bebani-rakyat',
                'kategori' => 'Politik',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/7vLeaa2S9ND7ndGXpOo6xaAF7H4XNRc0inPnSYt7.jpg',
                'ringkasan' => 'Komisi di DPR mengkritisi rencana kenaikan iuran BPJS Kesehatan yang dikabarkan akan diberlakukan pada tahun 2025, mendesak pemerintah mencari solusi berkelanjutan lain sebelum membebani masyarakat.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Rencana kenaikan iuran BPJS Kesehatan pada tahun anggaran 2025 mendapat reaksi keras dari Dewan Perwakilan Rakyat (DPR). Ketua Komisi yang mengawasi sektor kesehatan mengkritik langkah tersebut sebagai solusi yang tidak populer dan berpotensi menimbulkan gejolak di masyarakat. Kenaikan iuran dikhawatirkan akan membebani kelompok rentan yang baru saja pulih dari tekanan ekonomi. Kritik utama DPR berfokus pada ancaman defisit BPJS Kesehatan yang diperkirakan mencapai puluhan triliun rupiah. Para anggota dewan menduga penyebab utama defisit bukan hanya kurangnya iuran, melainkan meningkatnya utilisasi (penggunaan) layanan kesehatan dan kurang disiplinnya sebagian peserta dalam membayar iuran. Anggota DPR meminta pemerintah untuk melakukan kajian mendalam dan menawarkan solusi alternatif. Pilihan solusi yang diusulkan antara lain adalah perbaikan tata kelola, penertiban kepesertaan yang menunggak, dan optimalisasi sumber pendanaan negara lainnya, sejalan dengan program pemerintah yang fokus mengurangi beban finansial masyarakat.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Konflik Timur Tengah Memanas, Harga Emas Global Capai Rekor Tertinggi',
                'slug' => 'konflik-timur-tengah-memanas-harga-emas-global-capai-rekor-tertinggi',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/zzEihnEtngxXXFadwd5PuLRaNbj2f88cMv3po9Cb.jpg',
                'ringkasan' => 'Ketegangan geopolitik dan kebijakan moneter global memicu lonjakan harga emas. Emas menjadi aset paling aman (safe haven) di tengah ketidakpastian, berdampak pada inflasi di Indonesia.',
                'isi' => 'Jakarta, 15 Oktober 2025 - Ketidakpastian geopolitik di Timur Tengah dan kebijakan Bank Sentral Amerika Serikat yang cenderung dovish telah mendorong harga emas global mencapai rekor tertinggi sepanjang sejarah. Kenaikan harga emas ini, menurut Mendagri, dipicu oleh tren gold rush, di mana investor dan masyarakat mencari aset yang lebih aman untuk melindungi nilai uang mereka di tengah gejolak ekonomi. Lonjakan harga emas ini memiliki dampak langsung pada inflasi nasional. Badan Pusat Statistik (BPS) mencatat, emas perhiasan memberikan andil inflasi yang signifikan secara tahun kalender. Mendagri memastikan pemerintah terus memantau perkembangan harga ini dan inflasi. Selain emas, konflik juga menciptakan guncangan pada pasar energi. Ancaman penutupan Selat Hormuz berpotensi mendorong harga minyak Brent mendekati USD 110 per barel. Meskipun Indonesia memiliki keuntungan dari komoditas ekspor seperti batu bara, lonjakan harga minyak tetap berisiko menambah beban subsidi BBM, menuntut sinergi kuat antara kebijakan fiskal dan moneter.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'AS Kembali Veto Resolusi Gencatan Senjata Permanen di Gaza Dewan Keamanan PBB',
                'slug' => 'as-kembali-veto-resolusi-gencatan-senjata-permanen-di-gaza-dewan-keamanan-pbb',
                'kategori' => 'Internasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/yK2jEkWujWXXYSLswuDUd7cp2gwhPi58YGE8lIuY.jpg',
                'ringkasan' => 'Amerika Serikat sekali lagi menggunakan hak vetonya di Dewan Keamanan PBB untuk menolak resolusi yang menyerukan gencatan senjata permanen di Gaza, menimbulkan kritik dari negara-negara anggota lain.',
                'isi' => 'New York, 14 Oktober 2025 - Dewan Keamanan Perserikatan Bangsa-Bangsa (PBB) kembali gagal mencapai konsensus mengenai krisis di Gaza. Amerika Serikat (AS) menggunakan hak vetonya untuk menolak rancangan resolusi yang diajukan oleh [Sebutkan negara pengaju resolusi] yang menyerukan gencatan senjata segera dan permanen. Ini adalah kali kesekian AS memveto resolusi terkait konflik tersebut. Duta Besar negara-negara lain, termasuk perwakilan Indonesia, menyatakan kekecewaannya. Mereka menilai penggunaan veto untuk isu kemanusiaan dan kejahatan perang seharusnya tidak diperbolehkan, karena menghambat upaya perdamaian dan bantuan kemanusiaan. Di sisi lain, Duta Besar Israel di PBB berterima kasih kepada AS atas dukungan veto tersebut, menegaskan bahwa Israel tidak memerlukan pembenaran atas tindakannya di Gaza. Sementara upaya diplomatik terhenti di DKPBB, proposal gencatan senjata yang dimediasi oleh Mesir, Qatar, dan AS masih berjalan. Proposal tersebut mencakup tiga tahap: pembebasan sandera, penarikan tentara Israel dari Gaza, dan dimulainya rekonstruksi yang diawasi oleh PBB.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'BSSN Peringatkan Ancaman Siber 2025 Lebih Kompleks: Waspada AI Agentik dan Ransomware',
                'slug' => 'bssn-peringatkan-ancaman-siber-2025-lebih-kompleks-waspada-ai-agentik-dan-ransomware',
                'kategori' => 'Teknologi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/T9C96jTLXh9ElijQdLu7f6ag0iaVnI30y7ovZzhu.jpg',
                'ringkasan' => 'Badan Siber dan Sandi Negara (BSSN) memprediksi tahun 2025 menjadi tahun paling menantang dalam keamanan siber nasional, terutama dengan meningkatnya serangan ransomware dan ancaman dari Artificial Intelligence (AI) Agentik.',
                'isi' => 'Jakarta, 13 Oktober 2025 - BSSN mengeluarkan peringatan keras mengenai lanskap keamanan siber tahun 2025. Menurut laporan terbaru, penjahat siber kini semakin canggih dengan memanfaatkan AI untuk menciptakan malware yang sulit dideteksi dan melancarkan serangan ransomware yang lebih cepat dan efisien. Sektor kesehatan dan layanan publik diperkirakan menjadi target utama. Salah satu ancaman terbesar adalah AI Agentik, yang mampu mengeksploitasi ketergantungan pada open-source code dan menargetkan rantai pasokan. Selain itu, konflik geopolitik juga semakin terasa di ranah siber, dengan adanya peningkatan kampanye spionase dan disinformasi yang didorong oleh agenda politik. Untuk mengatasi ancaman ini, BSSN mendesak pemerintah segera memperkuat infrastruktur digital, menyelesaikan Peraturan Pemerintah turunan dari UU Perlindungan Data Pribadi (PDP), dan meningkatkan kapasitas sumber daya manusia di bidang keamanan siber. Kolaborasi antara pemerintah, sektor swasta, dan masyarakat sangat krusial untuk menjadikan Indonesia lebih tahan terhadap serangan siber.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'OJK Dorong Pembiayaan UMKM Lebih Cepat dan Murah, Kredit Hanya Tumbuh 1,35%',
                'slug' => 'ojk-dorong-pembiayaan-umkm-lebih-cepat-dan-murah-kredit-hanya-tumbuh-135',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/ZthnBHZtlNDQNzSGFoqIBSMkn8UEumVqn8pjt2eC.jpg',
                'ringkasan' => 'Otoritas Jasa Keuangan (OJK) merilis data terbaru yang menunjukkan pertumbuhan kredit UMKM melambat signifikan menjadi 1,35% per Agustus 2025, mendorong otoritas untuk menerbitkan aturan baru demi mempermudah akses pembiayaan.',
                'isi' => 'Jakarta, 12 Oktober 2025 - Sektor Usaha Mikro, Kecil, dan Menengah (UMKM) menghadapi tantangan serius. OJK melaporkan bahwa pertumbuhan kredit UMKM melambat drastis menjadi hanya 1,35% year-on-year (yoy) per Agustus 2025, jauh di bawah pertumbuhan kredit korporasi yang mencapai 10,79%. Kredit Modal Kerja juga hanya tumbuh 3,53% yoy. Kondisi ini menjadi alarm bagi perlunya intervensi kebijakan. Menanggapi hal tersebut, OJK telah menerbitkan aturan yang bertujuan mendorong penyaluran pembiayaan UMKM yang cepat, murah, dan mudah. Beberapa kebijakan yang diatur meliputi penyederhanaan persyaratan, skema pembiayaan khusus (termasuk penerimaan jaminan berupa kekayaan intelektual), dan percepatan proses bisnis melalui Pemeringkat Kredit Alternatif (PKA). Meskipun demikian, pelaku usaha diingatkan bahwa akses ke kredit tetap bergantung pada profil risiko. UMKM dengan rasio kredit bermasalah (Non-Performing Loan) yang tinggi cenderung sulit mendapat prioritas. OJK berharap dengan aturan baru ini, perbankan dan Lembaga Keuangan Non-Bank (LKNB) lebih aktif memberikan kemudahan akses, sambil tetap menjaga prinsip kehati-hatian.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Emas Antam Stagnan di Level Tertinggi Hari Ini, Investor Pantau Suku Bunga Global',
                'slug' => 'emas-antam-stagnan-di-level-tertinggi-hari-ini-investor-pantau-suku-bunga-global',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/RgA9DHgQsB1vYLzbX3LhUDGQh61rri5z99DeFW61.jpg',
                'ringkasan' => 'Harga emas batangan Logam Mulia (Antam) hari ini, 19 Oktober 2025, terpantau stagnan di level tinggi setelah sebelumnya mengalami kenaikan tajam akibat ketidakpastian geopolitik dan suku bunga AS.',
                'isi' => 'Jakarta, 11 Oktober 2025 - Harga emas batangan produksi PT Aneka Tambang Tbk (Antam) pada hari ini, Minggu (19/10), berada pada posisi stagnan setelah pergerakan volatil di pasar global minggu lalu. Harga dasar emas 1 gram tercatat berada di level Rp 2.428.000. Sementara harga buyback (jual kembali) berada pada posisi Rp 2.277.000 per gram. Stabilitas harga ini terjadi setelah harga emas global dipengaruhi oleh dua faktor utama: meningkatnya permintaan aset aman (safe haven) di tengah konflik geopolitik, dan ekspektasi pasar terhadap kebijakan suku bunga Bank Sentral AS (The Fed). Banyak investor menunggu kejelasan arah kebijakan The Fed sebelum mengambil posisi investasi jangka panjang. Bagi investor di Indonesia, harga emas yang tinggi ini memberikan keuntungan bagi pemilik yang ingin mencairkan asetnya. Namun, perlu dicatat bahwa harga yang tertera di gerai resmi Antam sudah termasuk pajak PPh 0,25%. Analis memprediksi harga emas akan tetap fluktuatif tetapi cenderung menguat hingga akhir tahun 2025, didukung oleh permintaan global yang tetap solid.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Mimpi Piala Dunia Pupus, Timnas Indonesia Tersingkir dari Kualifikasi Usai Dikalahkan Irak',
                'slug' => 'mimpi-piala-dunia-pupus-timnas-indonesia-tersingkir-dari-kualifikasi-usai-dikalahkan-irak',
                'kategori' => 'Olahraga',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/Jac0tc2yhXiSDAyQmeBcSjyUruI4259D7peEmncX.jpg',
                'ringkasan' => 'Timnas Indonesia U-17 gagal melaju ke Piala Dunia 2026 setelah menderita kekalahan 0-1 dari Irak pada laga terakhir putaran keempat kualifikasi zona Asia, mengakhiri perjalanan skuad asuhan Patrick Kluivert.',
                'isi' => 'Jeddah, 10 Oktober 2025 - Perjalanan bersejarah Tim Nasional Indonesia di Kualifikasi Piala Dunia 2026 harus terhenti di putaran keempat setelah takluk 0-1 dari Irak dalam pertandingan hidup-mati di Stadion King Abdullah Sports City. Kekalahan ini membuat Timnas Indonesia finis di posisi juru kunci Grup B tanpa poin, sekaligus memastikan kegagalan lolos ke putaran final Piala Dunia 2026. Indonesia yang dilatih oleh Patrick Kluivert sebenarnya memulai pertandingan dengan percaya diri, memeragakan pressing tinggi dan menciptakan beberapa peluang berbahaya melalui Thom Haye dan Kevin Diks. Namun, serangan balik cepat Irak di menit ke-76 berhasil menjebol gawang Maarten Paes, yang terbukti menjadi satu-satunya gol penentu. Sebelumnya, Indonesia juga kalah tipis 2-3 dari Arab Saudi. Ketua Umum PSSI, [Sebutkan nama Ketua Umum PSSI], menyampaikan permohonan maaf kepada seluruh masyarakat Indonesia. Meskipun kecewa, ia menegaskan bahwa hasil ini akan dijadikan evaluasi total dan PSSI akan fokus membangun tim untuk kompetisi regional yang akan datang.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Dominasi Horor Indonesia: Film Pabrik Gula Jadi Terlaris 2025 dengan 6 Juta Penonton',
                'slug' => 'dominasi-horor-indonesia-film-pabrik-gula-jadi-terlaris-2025-dengan-6-juta-penonton',
                'kategori' => 'Gaya Hidup',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/T8DS5bvJCtlzkraT6j0GaqT9AXfHTDuhVgZt6rL9.jpg',
                'ringkasan' => 'Industri film horor Indonesia mencatatkan kinerja gemilang sepanjang 2025. Film Pabrik Gula berhasil menempati posisi puncak sebagai film terlaris tahun ini dengan raihan lebih dari 6 juta penonton.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Tren film horor Indonesia terus menguat di box office nasional. Tahun 2025 mencatat rekor penonton yang luar biasa, dengan Pabrik Gula memimpin sebagai film terlaris dengan total lebih dari 6 juta penonton. Film yang menyuguhkan horor klasik dengan latar pabrik tua yang penuh misteri ini menunjukkan bahwa genre horor psikologis masih sangat diminati. Kesuksesan ini juga diikuti oleh film-film horor lainnya seperti Petaka Gunung Gede (3,2 juta penonton) yang diangkat dari mitos lokal, dan sekuel horor religi Qodrat 2 (2,2 juta penonton). Fenomena ini menegaskan bahwa produser film lokal semakin mahir dalam menggarap cerita yang relevan dengan budaya dan mitos Indonesia. Analis film memprediksi dominasi horor ini akan berlanjut hingga akhir tahun, terutama dengan rilisnya film-film yang sangat dinantikan seperti Utusan Iblis dan Ketindihan. Keberhasilan ini tidak hanya berdampak pada pendapatan, tetapi juga mendorong kreativitas sineas muda untuk mengeksplorasi cerita horor dengan berbagai sub-genre yang lebih beragam.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Misi M2/Resilience Jepang Fokus pada Oksigen di Bulan, Siap Luncur Januari 2026',
                'slug' => 'misi-m2resilience-jepang-fokus-pada-oksigen-di-bulan-siap-luncur-januari-2026',
                'kategori' => 'Internasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/1RmA2Z9y0TgfaU9TeJ20uMWQFXceCzAPYo0h8UGQ.jpg',
                'ringkasan' => 'Badan Eksplorasi Antariksa Jepang (JAXA) tengah bersiap meluncurkan misi M2/Resilience pada Januari 2026. Misi ini membawa pendarat dan mikro-rover untuk menguji teknologi pemisahan air, langkah krusial menuju kolonisasi Bulan.',
                'isi' => 'Tokyo, 19 Oktober 2025 - Setelah sukses dengan beberapa misi luar angkasa sebelumnya, Jepang kini mengalihkan fokus ke Bulan dengan misi ambisius M2/Resilience. Misi ini dijadwalkan meluncur pada awal tahun 2026 dan menjadi bagian penting dari upaya global untuk eksplorasi Bulan jangka panjang. Inovasi utama dari misi ini adalah pengujian teknologi pemisahan air untuk menghasilkan oksigen dan hidrogen langsung di permukaan Bulan. Teknologi ini sangat vital. Jika berhasil, produksi oksigen lokal dapat mendukung kelangsungan hidup astronaut dan menjadi bahan bakar roket untuk misi kembali ke Bumi atau ke Mars, mengurangi biaya logistik secara signifikan. Selain itu, misi ini juga akan menguji sistem navigasi presisi tinggi untuk pendaratan yang akurat dan kemampuan otonom mikro-rover. M2/Resilience menempatkan Jepang di garis depan eksplorasi antariksa bersama AS dan Tiongkok. Meskipun roket H2A Jepang sudah pensiun pada Juni 2025, peluncuran misi ini akan memanfaatkan roket generasi terbaru, H3, yang diharapkan memangkas biaya operasional dan meningkatkan daya saing industri luar angkasa Jepang.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Kenyamanan Mengalahkan Jarak, 78% Wisatawan Indonesia Pilih Staycation di Hotel Mewah',
                'slug' => 'kenyamanan-mengalahkan-jarak-78-wisatawan-indonesia-pilih-staycation-di-hotel-mewah',
                'kategori' => 'Gaya Hidup',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/BF7Yqk6sEk1r6Z4hTcrWkSsOqJNn8uh8pBDdDh8T.jpg',
                'ringkasan' => 'Survei pariwisata 2025 menunjukkan preferensi masyarakat Indonesia yang semakin condong ke tren staycation (staying on vacation), di mana 78% responden memilih menghabiskan waktu di hotel karena faktor kenyamanan dan fasilitas.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Liburan tidak harus bepergian jauh. Inilah inti dari tren staycation yang mendominasi pariwisata Indonesia pada tahun 2025. Hasil survei menunjukkan bahwa hampir delapan dari sepuluh wisatawan lokal memilih untuk menghabiskan sebagian besar, bahkan seluruh waktu liburan mereka, di hotel. Faktor utama yang mendorong tren ini adalah keinginan untuk beristirahat tanpa stres perjalanan (travel burnout) dan menikmati fasilitas hotel secara maksimal. Pemandangan kamar menjadi daya tarik utama, dengan 56% wisatawan menjadikannya pertimbangan penting saat memilih akomodasi. Selain itu, peningkatan kesadaran lingkungan juga memengaruhi pilihan. Sekitar 95% orang Indonesia bersedia membayar lebih untuk penginapan yang menerapkan konsep ramah lingkungan (eco-friendly). Kota-kota besar seperti Malang dan Jakarta menjadi pusat staycation favorit, menawarkan berbagai pilihan mulai dari hotel butik hingga resort yang menyatu dengan alam. Industri perhotelan merespons tren ini dengan menawarkan paket lengkap, termasuk kegiatan keluarga di dalam properti, yang menegaskan bahwa fokus liburan telah bergeser dari destinasi ke pengalaman.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Pabrik Gula Puncaki Box Office, Film Horor Indonesia Buktikan Kualitas dan Daya Tarik Lokal',
                'slug' => 'pabrik-gula-puncaki-box-office-film-horor-indonesia-buktikan-kualitas-dan-daya-tarik-lokal',
                'kategori' => 'Gaya Hidup',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/KhOs6UOgXIHlL9tWBZb0mvdYd8oG5BKo60xmz3hu.jpg',
                'ringkasan' => 'Film horor Pabrik Gula resmi dinobatkan sebagai film terlaris di Indonesia pada 2025 dengan capaian 6 juta lebih penonton. Kesuksesan ini mengukuhkan dominasi genre horor di pasar film nasional.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Industri film Indonesia menunjukkan kekuatan yang luar biasa tahun ini, dipimpin oleh genre horor. Film Pabrik Gula berhasil memikat lebih dari 6.012.355 penonton, menjadikannya film terlaris tahun 2025. Keberhasilan ini dikaitkan dengan perpaduan horor klasik yang mencekam dengan latar pabrik tua yang menyimpan kisah kelam. Diikuti ketat oleh film horor dengan mitos lokal, Petaka Gunung Gede, yang berhasil meraih 3,2 juta penonton. Sektor horor religi juga tak kalah, terbukti dari kesuksesan sekuel Qodrat 2 yang mencatatkan 2,2 juta penonton. Total perolehan penonton ini menunjukkan peningkatan minat masyarakat terhadap film lokal berkualitas tinggi. Kenaikan signifikan ini menjadi angin segar bagi industri perfilman. Selain menghibur, film horor kini dianggap sebagai sarana efektif untuk mengeksplorasi cerita dan legenda Indonesia, sekaligus menjadi motor penggerak ekonomi kreatif. Kehadiran film-film horor baru di akhir tahun, seperti Utusan Iblis dan Muslihat, diprediksi akan terus mempertahankan tren positif ini.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Investor Cemas Geopolitik, Harga Emas Batangan Antam Tembus Rp 2,4 Juta per Gram',
                'slug' => 'investor-cemas-geopolitik-harga-emas-batangan-antam-tembus-rp-24-juta-per-gram',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/mQ3E1wfWW1zY1RXPadqipF8c9kW8UzJki1j29Mns.jpg',
                'ringkasan' => 'Harga emas batangan Logam Mulia (Antam) pada 19 Oktober 2025 tercatat stagnan di level sangat tinggi, didukung permintaan investor yang mencari aset aman (safe haven) di tengah ketidakpastian global dan inflasi.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Harga jual emas batangan PT Antam Tbk hari ini, Minggu (19/10), kembali mencatatkan harga yang stabil setelah fluktuasi tajam minggu lalu. Emas Antam 1 gram dibanderol pada Rp 2.428.000. Harga jual ini sudah mendekati level psikologis tertinggi, sementara harga jual kembali (buyback) berada di posisi Rp 2.277.000 per gram. Kenaikan harga emas ini didorong kuat oleh kekhawatiran geopolitik global, terutama di Timur Tengah, yang mendorong Bank Sentral dan investor ritel memindahkan modal ke aset yang lebih aman. Di pasar domestik, permintaan emas juga didorong oleh inflasi yang masih tinggi, menjadikan emas sebagai instrumen efektif untuk melindungi kekayaan dari penurunan nilai mata uang. Analis merekomendasikan investor untuk mencermati keputusan suku bunga The Fed mendatang. Jika The Fed mulai menahan atau menurunkan suku bunga, ini dapat memberikan dorongan lebih lanjut pada harga emas. Bagi yang berencana membeli, disarankan untuk memanfaatkan harga stagnan ini sebelum lonjakan berikutnya terjadi.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Kalah Tipis dari Arab Saudi 2-3, Pelatih Timnas Sesalkan Gol Mudah di Awal Laga',
                'slug' => 'kalah-tipis-dari-arab-saudi-2-3-pelatih-timnas-sesalkan-gol-mudah-di-awal-laga',
                'kategori' => 'Nasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/IsWR7OpRoGY9iCpaHZX90uLzMldfmVLviqmisuND.jpg',
                'ringkasan' => 'Timnas Indonesia memulai Kualifikasi Piala Dunia 2026 putaran keempat dengan kekalahan dramatis 2-3 dari Arab Saudi. Meskipun sempat unggul, performa tim asuhan Patrick Kluivert menurun akibat kebobolan gol-gol mudah di babak pertama.',
                'isi' => 'Riyadh, 19 Oktober 2025 - Tim Nasional Indonesia U-17 harus mengakui keunggulan Arab Saudi dengan skor akhir 2-3 dalam laga pembuka Kualifikasi Piala Dunia 2026 Grup B. Pertandingan yang digelar di King Abdullah Sports City berlangsung sengit, namun pelatih Timnas, Patrick Kluivert, menyayangkan kegagalan timnya mempertahankan keunggulan. Indonesia sempat memimpin melalui eksekusi penalti Kevin Diks di menit ke-11. Namun, keunggulan itu tak bertahan lama. Arab Saudi membalikkan keadaan lewat gol balasan dan penalti yang terjadi akibat kesalahan di lini belakang. Marc Klok dan Yakob Sayuri terlibat dalam kesalahan yang berujung gol lawan, yang sangat disesalkan Kluivert. Meskipun tertinggal 1-3, Timnas menunjukkan semangat pantang menyerah. Indonesia berhasil memperkecil kettertinggalan menjadi 2-3 lewat penalti Kevin Diks menjelang akhir pertandingan. Sayangnya, upaya menekan di 9 menit injury time tidak membuahkan hasil. Kekalahan ini menempatkan Indonesia di posisi juru kunci sementara, menjadikan laga berikutnya melawan Irak sebagai penentu nasib.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Musim Hujan Datang, Kemenkes Minta Masyarakat Waspada Kenaikan Kasus Flu Musiman',
                'slug' => 'musim-hujan-datang-kemenkes-minta-masyarakat-waspada-kenaikan-kasus-flu-musiman',
                'kategori' => 'Kesehatan',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/FqjHPv1c5iG3FenagiTDT6Nl6zgoCKz8UGCwIz3g.jpg',
                'ringkasan' => 'Kementerian Kesehatan (Kemenkes) mengeluarkan imbauan kepada masyarakat untuk kembali meningkatkan kewaspadaan dan protokol kesehatan, menyusul adanya peningkatan kasus infeksi saluran pernapasan atas (ISPA) seiring datangnya musim hujan.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Pergantian musim dari kemarau ke hujan selalu membawa risiko kesehatan, terutama peningkatan kasus Flu Musiman dan Infeksi Saluran Pernapasan Akut (ISPA). Kepala Biro Komunikasi dan Pelayanan Publik Kemenkes, [Sebutkan Nama Pejabat Kemenkes], mengimbau masyarakat agar tidak lengah. Data Puskesmas di sejumlah daerah menunjukkan lonjakan kunjungan pasien dengan keluhan batuk, pilek, dan demam dalam dua minggu terakhir. Kemenkes menyarankan agar masyarakat yang sakit tetap menggunakan masker saat berada di ruang publik atau transportasi umum untuk mencegah penularan. Prioritas diberikan kepada kelompok rentan, seperti lansia dan anak-anak, untuk segera mendapatkan vaksinasi influenza. Selain itu, masyarakat diimbau untuk menjaga daya tahan tubuh dengan mengonsumsi makanan bergizi, cukup istirahat, dan segera memeriksakan diri ke fasilitas kesehatan jika gejala memburuk. Kesiapsiagaan fasilitas kesehatan, termasuk ketersediaan obat dan tempat tidur, juga sudah ditingkatkan di tingkat daerah untuk mengantisipasi puncak kasus.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => '5 Rekomendasi Kafe Instagramable di Jakarta Selatan, Tawarkan Konsep Unik dan Co-working Space',
                'slug' => '5-rekomendasi-kafe-instagramable-di-jakarta-selatan-tawarkan-konsep-unik-dan-co-working-space',
                'kategori' => 'Gaya Hidup',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/OwqevSu4K7hnUEBASGp67e2Uac7uElpMc18B84yf.jpg',
                'ringkasan' => 'Jakarta Selatan, sebagai pusat gaya hidup urban, terus menyajikan kafe dan tempat nongkrong baru. Kami merangkum lima rekomendasi kafe terbaru yang tidak hanya menyajikan kopi berkualitas, tetapi juga desain yang instagramable dan fasilitas kerja yang nyaman.',
                'isi' => 'Jakarta, 19 Oktober 2025 - Budaya kopi dan co-working di Jakarta Selatan tidak pernah mati. Seiring meningkatnya tren bekerja fleksibel (work from anywhere), kafe bukan hanya tempat minum kopi, tetapi juga ruang kreatif. Lima kafe terbaru di kawasan Senopati, Kemang, dan Blok M menjadi sorotan karena desainnya yang unik. Salah satunya, The Greenhaus, yang menawarkan konsep rumah kaca dengan tanaman indoor yang subur, menjadikannya lokasi sempurna untuk foto sekaligus tempat rapat santai. Selain estetika, faktor kenyamanan dan koneksi internet menjadi penentu. Kafe-kafe ini kini wajib menyediakan high-speed Wi-Fi dan stop kontak di setiap meja. Tren minuman juga bergeser ke arah artisan coffee dan minuman berbasis tumbuhan (plant-based milk), sejalan dengan gaya hidup sehat. Kepala Asosiasi Kuliner Jakarta, [Sebutkan Nama Tokoh], menyatakan bahwa sektor kafe tidak hanya mendorong pertumbuhan UMKM, tetapi juga menciptakan ekosistem kreatif. Ia menyarankan para pemilik kafe untuk terus berinovasi, tidak hanya pada menu, tetapi juga pada pengalaman pelanggan secara keseluruhan.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Pasar Kendaraan Listrik Memanas, Produsen Lokal Siap Luncurkan Model Baru dengan Harga di Bawah Rp 250 Juta',
                'slug' => 'pasar-kendaraan-listrik-memanas-produsen-lokal-siap-luncurkan-model-baru-dengan-harga-di-bawah-rp-250-juta',
                'kategori' => 'Otomotif',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/muQviIvHtKIratUsM04ClgdCIojhKFnoQNOFzb6c.jpg',
                'ringkasan' => 'Menyambut insentif pemerintah, beberapa produsen otomotif lokal dan kemitraan siap meluncurkan model mobil listrik baru dengan harga yang lebih terjangkau, menargetkan segmen menengah dan first-time buyer EV.',
                'isi' => '<b>Karawang, 19 Oktober 2025</b> - Persaingan di pasar kendaraan listrik (EV) Indonesia semakin memanas. Setelah dominasi merek asing, kini produsen lokal menunjukkan taringnya dengan rencana peluncuran EV yang fokus pada keterjangkauan. Salah satu pabrikan yang berbasis di Karawang dikabarkan siap merilis model city car listrik dengan banderol di bawah Rp 250 juta.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'BMKG Ingatkan Kesiapsiagaan Nasional, Cuaca Ekstrem Intai Wilayah Indonesia Hingga Akhir Bulan',
                'slug' => 'bmkg-ingatkan-kesiapsiagaan-nasional-cuaca-ekstrem-intai-wilayah-indonesia-hingga-akhir-bulan',
                'kategori' => 'Nasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/yOVpsLugmccG5Y9FzjHUchQ9dQqJbDurUxI26QK4.jpg',
                'ringkasan' => 'Badan Meteorologi, Klimatologi, dan Geofisika (BMKG) mengeluarkan peringatan dini potensi cuaca ekstrem, termasuk hujan lebat disertai angin kencang, di sejumlah wilayah, mengimbau masyarakat meningkatkan kewaspadaan.',
                'isi' => '<b>Jakarta, 19 Oktober 2025</b> - BMKG kembali merilis peringatan dini cuaca ekstrem yang diprediksi akan terus melanda beberapa wilayah Indonesia dalam periode masa peralihan musim ini.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Kinerja Positif Laba Bersih Emiten Agregat Naik 21%, Sektor Bahan Baku Jadi Raja',
                'slug' => 'kinerja-positif-laba-bersih-emiten-agregat-naik-21-sektor-bahan-baku-jadi-raja',
                'kategori' => 'Ekonomi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/OqY9uO3W9iZOixijT1VU8KtOUZkE7EeCzc2Mjnkc.jpg',
                'ringkasan' => 'Kinerja emiten di Bursa Efek Indonesia (BEI) pada Semester I-2025 menunjukkan pertumbuhan laba bersih agregat yang signifikan. Sektor Bahan Baku mencatat pertumbuhan laba tertinggi, mengungguli Sektor Konsumer dan Teknologi.',
                'isi' => '<b>Jakarta, 19 Oktober 2025</b> - Pasar modal nasional mencatatkan kinerja positif pada paruh pertama 2025.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Final Dramatis Piala AFF U-23: Indonesia Tunduk 0-1 dari Vietnam, Harus Puas Jadi Runner-up',
                'slug' => 'final-dramatis-piala-aff-u-23-indonesia-tunduk-0-1-dari-vietnam-harus-puas-jadi-runner-up',
                'kategori' => 'Olahraga',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/uuqzI1q1QVSQ4Wq2CxXozmRkiRCBHcI9QyC74Byd.jpg',
                'ringkasan' => 'Timnas Indonesia U-23 gagal meraih gelar juara Piala AFF U-23 2025 setelah kalah tipis 0-1 dari rival abadi, Vietnam U-23, dalam laga final yang berlangsung sengit di Stadion Utama Gelora Bung Karno (SUGBK).',
                'isi' => '<b>Jakarta, 19 Oktober 2025</b> - Mimpi Garuda Muda untuk mengangkat trofi Piala AFF U-23 2025 di hadapan publik sendiri harus pupus.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Indonesia Sentris Jadi Prioritas RPJPN 2025-2045, Pembangunan Infrastruktur Luar Jawa Dikebut',
                'slug' => 'indonesia-sentris-jadi-prioritas-rpjpn-2025-2045-pembangunan-infrastruktur-luar-jawa-dikebut',
                'kategori' => 'Nasional',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/LLfai6tvqU471PKqLr5ccqnFPhk6mPrbKZprQfAZ.jpg',
                'ringkasan' => 'Pemerintah memastikan pembangunan infrastruktur tidak lagi berpusat di Jawa, sejalan dengan visi "Indonesia Sentris" dalam Rencana Pembangunan Jangka Panjang Nasional (RPJPN) 2025-2045 untuk menciptakan pemerataan ekonomi.',
                'isi' => '<b></b><b>Jakarta, 19 Oktober 2025</b> - Presiden [Sebutkan nama Presiden] kembali menegaskan komitmen pemerintah dalam melanjutkan pembangunan infrastruktur yang inklusif.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Kesehatan Mental Jadi Prioritas, Generasi Muda Tuntut Work-Life Balance dan Kerja Fleksibel',
                'slug' => 'kesehatan-mental-jadi-prioritas-generasi-muda-tuntut-work-life-balance-dan-kerja-fleksibel',
                'kategori' => 'Gaya Hidup',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/lxCwbbL3XNT092m5NAMPFX893VDbO4rur40nFtcs.jpg',
                'ringkasan' => 'Tren Work-Life Balance (WLB) semakin menguat pada 2025. Generasi muda menuntut fleksibilitas waktu dan lokasi kerja, menjadikan kesehatan mental sebagai komponen penting dalam produktivitas, bukan sekadar pelengkap.',
                'isi' => '<b>Jakarta, 19 Oktober 2025</b> - Budaya kerja di Indonesia mengalami transformasi signifikan.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'Kabar Baik Venture Capital: Startup Edutech Xendit Raih Pendanaan Seri B US$ 10 Juta',
                'slug' => 'kabar-baik-venture-capital-startup-edutech-xendit-raih-pendanaan-seri-b-us-10-juta',
                'kategori' => 'Teknologi',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/wlY1OS10JdHqSJqDF0tpJaaQo0Ii9I4Sipslzdzc.jpg',
                'ringkasan' => 'Startup teknologi pendidikan (edutech) lokal, Xendit, berhasil menutup putaran pendanaan Seri B senilai US$ 10 juta. Dana segar ini akan digunakan untuk ekspansi program vokasi dan memperluas jangkauan layanan ke seluruh Indonesia Timur.',
                'isi' => '<b>Jakarta, 19 Oktober 2025</b> - Setelah mengalami musim dingin investasi yang panjang, sektor teknologi Indonesia kembali menunjukkan tanda-tanda pemulihan.',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
            [
                'judul' => 'PSSI Gelar Seleksi Pemain U-17 Gelombang Kedua, Jaring Talenta Daerah untuk Piala Asia 2026',
                'slug' => 'pssi-gelar-seleksi-pemain-u-17-gelombang-kedua-jaring-talenta-daerah-untuk-piala-asia-2026',
                'kategori' => 'Olahraga',
                'penulis' => 'Tim Redaksi',
                'foto' => 'artikel/jtNWTM2GuJIXWv4Thb2gBuTsHEFtUZcVNqqaLWlQ.jpg',
                'ringkasan' => 'PSSI kembali menggelar seleksi Timnas U-17 Indonesia, kali ini fokus pada 34 pemain muda dari akademi regional dan SSB di seluruh Indonesia sebagai persiapan jangka panjang menuju Piala Asia U-17 2026.',
                'isi' => '<p>Jakarta, 19 Oktober 2025 - PSSI (Persatuan Sepak Bola Seluruh Indonesia) melalui Direktur Tekniknya, mengumumkan dimulainya seleksi gelombang kedua Tim Nasional U-17.</p>',
                'status' => 'terbit',
                'tanggal_terbit' => '2025-10-19 00:00:00',
            ],
        ];

        foreach ($artikelData as $artikel) {
            Artikel::create(array_merge($artikel, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
